---
title: "Causal Discovery"
author: "V Didelez, C W Bang"
date: "28 11 2025"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Causal Discovery}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.width = 6, 
                      message = FALSE, 
                      warning = FALSE, 
                      cache = FALSE, 
                      eval = FALSE,
                      echo = TRUE)
```

```{r packages}
library(tidyr)
library(pcalg)
library(DataTrainCausalLearning)
```

# Descriptive statistics

```{r read_tcga}
data("tcgas")
```

```{r dim_tcga}
dim(tcgas)
```

```{r head_tcga}
head(tcgas)
```

```{r plot_tcga}
plot(tcgas, cex = 0.3)
```

```{r hist_tcga}
tcgas %>% 
  tidyr::pivot_longer(
    cols = everything(),
    names_to  = "key",
    values_to = "value"
  ) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(col = "black", fill = "white") + 
  theme_light() +
  facet_wrap(~ key)

```

# PC-algorithm

```{r fitpc_tcga}
pcfit <- pc(
  suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]), # correlation matrix and the number of observations
  indepTest = gaussCItest, # our choice of independence test
  alpha = 0.05, # our choice of "significance level"
  labels = colnames(tcgas), # variable names
  maj.rule = T, solve.confl = T, u2pd = "relaxed"
)
```

```{r fitalpha_tcga}
plot(pc(
  suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]),
  indepTest = gaussCItest,
  alpha = 0.01,
  labels = colnames(tcgas),
  maj.rule = T, solve.confl = T, u2pd = "relaxed"
)@graph, main = "alpha = 1%")

plot(pcfit@graph, main = "alpha = 5%")

plot(pc(
  suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]),
  indepTest = gaussCItest,
  alpha = 0.1,
  labels = colnames(tcgas),
  maj.rule = T, solve.confl = T, u2pd = "relaxed"
)@graph, main = "alpha = 10%")
```

# FCI-algorithm

```{r fitfci}
fcifit <- fci(
  suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]),
  indepTest = gaussCItest,
  alpha = 0.05,
  labels = colnames(tcgas),
  maj.rule = T,
  selectionBias = F
)
```

```{r plotfci}
plot(fcifit)
```

# GES-algorithm

```{r fitges_tcga}
gesfit <- ges(new("GaussL0penObsScore", tcgas))
```

```{r plotges}
plot(gesfit$essgraph)
```

# LiNGAM

```{r fitlingam_tcga}
lingamfit <- lingam(tcgas)
```

```{r lingamfct}
lingam2graph <- function(fit,data){
  
  amat <- t(fit$Bpruned!=0)
  
  colnames(amat) <- colnames(data)
  
  output <- as(amat, "graphNEL")
  
  return(output)
}

```

```{r graphlingam_tcga}
lingamgraph <- lingam2graph(fit = lingamfit, # fitted object
                            data = tcgas # data used to fit the object
                            )
```

```{r plotlingam}
plot(lingamgraph)
```

# (Randomized) Kernel Conditional Independence (CI) test

```{r kpcfit}
pcfit_kernel05 <- pc(suffStat = list(data = tcgas),
                     indepTest = RCIT, 
                     alpha = 0.05,
                     labels = colnames(tcgas),
                     maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed"
                     )

pcfit_kernel10 <- pc(suffStat = list(data = tcgas),
                     indepTest = RCIT,
                     alpha = 0.1,
                     labels = colnames(tcgas),
                     maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed"
                     )

# plot both graphs
par(mfrow = c(1,2))

plot(pcfit_kernel05, main = "alpha = 5%")
plot(pcfit_kernel10, main = "alpha = 10%")
```

# Generalised Covariance Measure
Use the wrapper functions `RCIT` and `GCM` that are provided in this package.


<!-- ```{r gcm_lib} -->
<!-- library(GeneralisedCovarianceMeasure) -->
<!-- ``` -->



```{r pcfit_gcm}
pcfit_gcm05 <- pc(suffStat = list(data = tcgas), 
                  indepTest = GCM,
                  alpha = 0.05,
                  labels = colnames(tcgas),
                  maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed",
                  verbose = TRUE
                  )


pcfit_gcm10 <- pc(suffStat = list(data = as.matrix(tcgas), alpha = alpha),
                  indepTest = GCM,
                  alpha = 0.1,
                  labels = colnames(tcgas),
                  maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed"
                  )
```

```{r plot_gcm}
par(mfrow = c(1,2))

plot(pcfit_gcm05, main = "alpha = 5%")
plot(pcfit_gcm10, main = "alpha = 10%")
```

# Discrete data

```{r fit_dis}
data("tcgadisc")
```

```{r disICfunc}
disCItest_mod <- function(x, y, S, suffStat){
  if (is.data.frame(dm <- suffStat$dm)) 
        dm <- data.matrix(dm)
  else stopifnot(is.matrix(dm))
  nlev <- suffStat$nlev
  adaptDF <- suffStat$adaptDF
  gSquareDis(x = x, y = y, S = S, dm = dm, nlev = nlev, adaptDF = adaptDF,
             verbose = FALSE, n.min = -1)
}
```

```{r fitdis}

pcfit_d05 <- pc(suffStat = list(dm = tcgadisc, adaptDF = F),
                indepTest = disCItest_mod,
                alpha = 0.05,
                labels = colnames(tcgadisc),
                maj.rule = T, solve.confl = T, u2pd = "relaxed"
                )

pcfit_d10 <- pc(suffStat = list(dm = tcgadisc, adaptDF = F),
                indepTest = disCItest_mod,
                alpha = 0.1,
                labels = colnames(tcgadisc),
                maj.rule = T, solve.confl = T, u2pd = "relaxed"
                )
```

```{r plot_dis}
par(mfrow = c(1,2))

plot(pcfit_d05@graph, main = "alpha = 5%")
plot(pcfit_d10@graph, main = "alpha = 10%")
```




# Comparison

```{r compare_fit}
par(mfrow = c(1,2))
plot(pcfit@graph, main = "PC (left) and FCI (right)")
plot(fcifit)
par(mfrow = c(1,2))
plot(gesfit$essgraph, main = "GES")
plot(lingamgraph, main = "LiNGAM")
par(mfrow = c(1,2))
plot(pcfit_gcm10@graph, main = "GCM")
plot(pcfit_kernel10@graph, main = "Kernel")
par(mfrow = c(1,1))
plot(pcfit_d10@graph, main = "Discrete")
```

```{r possan}
possAn(t(as(as(gesfit$essgraph, "graphNEL"), "Matrix")), # the graph has to be specified as a matrix
       x = 4, # indicates the position of the variables of interest
       type = "cpdag" # type of graph
       )
```

```{r names_possan}
colnames(tcgas)[c(1,4,5,6,7)]
```

```{r possde}
possDe(t(as(as(gesfit$essgraph, "graphNEL"), "Matrix")), 
       x = 4, 
       type = "cpdag" 
       )
```

```{r names_possde}
colnames(tcgas)[c(2,3,4,8)]
```

# IDA algorithm

```{r lm1_fcga}
summary(lm(CDK6 ~ HMGA2 + BAX + CDKN2A + CDKN1A + MDM2 + SERPINE1 + THBS1, data = tcgas))$coefficients
```

```{r print_names}
names(tcgas)
```

```{r ida_local}
ida(x.pos = 4, # position of HMGA2 in the dataset 
    y.pos = 8, # position of CDK6 in the dataset
    cov(tcgas), # covariance matrix of the dataset
    graphEst = as(gesfit$essgraph,"graphNEL"), # estimated graph
    method = "local", # type of adjustment set
    type = "cpdag", # type of the estimated graph
    verbose = TRUE
      )
```

```{r, echo = F}
ida(x.pos = 4, # position of HMGA2 in the dataset 
    y.pos = 8, # position of CDK6 in the dataset
    cov(tcgas), # covariance matrix of the dataset
    graphEst = as(gesfit$essgraph,"graphNEL"), # estimated graph
    method = "local", # type of adjustment set
    type = "cpdag", # type of the estimated graph
    verbose = TRUE
      ) -> idaest1
```

```{r lm2_fcga}
summary(lm(CDK6 ~ HMGA2 + SERPINE1 + THBS1, data = tcgas))$coefficients
```

```{r ida_optimal}
ida(x.pos = 4,
    y.pos = 8,
    cov(tcgas),
    graphEst = as(gesfit$essgraph,"graphNEL"),
    method = "optimal",
    type = "cpdag",
    verbose = TRUE
      )
```

```{r lm3_fcga}
summary(lm(CDK6 ~ HMGA2 + SERPINE1 + THBS1 + MDM2, data = tcgas))$coefficients
```

```{r ida_alt}
ida(x.pos = 5,
    y.pos = 8,
    cov(tcgas),
    graphEst = as(gesfit$essgraph,"graphNEL"),
    method = "local",
    type = "cpdag",
    verbose = T
      )
```
